[package]
name = "imgvwr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
iced = { version = "0", features = ["debug", "image"] }
serde = { version = "1", features = ["derive"] }
toml = "0"
image = "0"
dirs = "5"
